---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paul-app
  labels:
    app: paul-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: paul-app
  template:
    metadata:
      labels:
        app: paul-app
    spec:
      containers:
      - name: paul-app
        image: pjpaul/paul-app:14
        ports:
        - containerPort: 8080

  

